name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t tapas710/my-nextjs-app .
      - name: Login to docker hub
        run: docker login -u tapas710 -p Tapas710@
      - name: Publish image to docker hub
        run: docker push tapas710/my-nextjs-app

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull tapas710/my-nextjs-app
      - name: Delete old container
        run: docker rm -f nextjs-app-container  
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nextjs-app-container tapas710/my-nextjs-app
